name: Deploy Vite Project

on:
  push:
    branches:
      - gh-pages  # Ensure you're deploying from the correct branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up environment variable
        run: echo "VITE_GITHUB_API_KEY=${{ secrets.GITHUB_API_KEY }}" >> $GITHUB_ENV

      - name: Debug environment variables (optional)
        run: echo "VITE_GITHUB_API_KEY=$VITE_GITHUB_API_KEY"  # Debugging to verify secret injection

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist  # Ensure this is your build output directory
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is used for deploying to gh-pages
